import { Investasi_ComponentStylesCard } from "./comp_card_border_and_background";
import { Investasi_ComponentBoxDaftarBerita } from "./detail/comp_box_daftar_berita";
import { Investasi_ComponentBoxDaftarDokumen } from "./detail/comp_box_daftar_dokumen";
import { Investasi_ComponentBoxProspektus } from "./detail/comp_box_prospektus";
import { Investasi_ComponentBoxDetailData } from "./detail/saham_saya/comp_detail_data";
import { Investasi_ComponentBoxHargaDanLembarSaham } from "./detail/saham_saya/comp_harga_dan_lembar";
import { Investasi_ComponentBoxProgress } from "./detail/saham_saya/comp_progress_saham";
import { Investasi_ComponentCardBeranda } from "./main/comp_card_beranda";
import { Investasi_ComponentCardDaftarTransaksi } from "./main/comp_card_daftar_transaksi";
import { Investasi_ComponentSahamSaya } from "./main/comp_card_saham_saya";
import { Investasi_ComponentFooterMain } from "./main/comp_footer_main";
import { Investasi_ComponentCardPortofolioPublish } from "./main/comp_card_portofolio_publish";
import { Investasi_ComponentButtonUpdateBeranda } from "./main/comp_update_beranda";
import { Investasi_ComponentCardPortofolio_NotPublish } from "./main/comp_card_portofolio_not_publish";
import { Investasi_ComponentButtonCreateNewInvestasi } from "./button/comp_button_create_new_investasi";
import { Investasi_ComponentTitleAndValueInDetail } from "./detail/comp_title_and_value_in_detail";
import { Investasi_ComponentDetailDataNonPublish } from "./detail/comp_detail_data_non_publish";
import { Investasi_ComponentButtonUpdateDataInvestasi } from "./button/comp_button_update_investasi";
import { Investasi_ComponentCardRekapDocument } from "./detail/comp_card_rekap_document";
import { Investasi_ComponentCardDaftarDocument } from "./detail/comp_card_daftar_document";

export { Investasi_ComponentFooterMain };
export { Investasi_ComponentCardBeranda };
export { Investasi_ComponentButtonUpdateBeranda };
export { Investasi_ComponentCardDaftarTransaksi };
export { Investasi_ComponentSahamSaya };
export { Investasi_ComponentStylesCard };
export { Investasi_ComponentBoxProspektus };
export { Investasi_ComponentBoxDaftarDokumen };
export { Investasi_ComponentBoxDaftarBerita };
export { Investasi_ComponentBoxHargaDanLembarSaham };
export { Investasi_ComponentBoxProgress };
export { Investasi_ComponentBoxDetailData };
export { Investasi_ComponentCardPortofolioPublish };
export { Investasi_ComponentCardPortofolio_NotPublish };
export { Investasi_ComponentButtonCreateNewInvestasi };
export { Investasi_ComponentTitleAndValueInDetail };
export { Investasi_ComponentDetailDataNonPublish };
export { Investasi_ComponentButtonUpdateDataInvestasi };
export { Investasi_ComponentCardRekapDocument };
export { Investasi_ComponentCardDaftarDocument };
