import { Investasi_UiFileViewProspektus } from "./file_view/ui_file_view_prospektus";
import { Investasi_UiInvoice } from "./transaksi/ui_invoice";
import { Investasi_UiMetodePembayaran } from "./transaksi/ui_metode_pembayaran";
import { Investasi_UiProsesPembelian } from "./transaksi/ui_proses_pembelian";
import { Investasi_UiProsesTransaksi } from "./transaksi/ui_proses_transaksi";
import { Investasi_UiBeranda } from "./main/ui_beranda";
import { Investasi_UiLayoutMain } from "./main/ui_layout_main";
import { Investasi_UiDaftarTransaksi } from "./main/ui_transaksi";
import { Investasi_UiTransaksiBerhasil } from "./status_transaksi/ui_transaksi_berhasil";
import { Investasi_UiFileViewDokumen } from "./file_view/ui_file_view_dokumen";
import { Investasi_UiSahamSaya } from "./main/ui_saham_saya";
import { Investasi_UiDetailSahamSaya } from "./detail/ui_detail_saham_saya";
import { Investasi_UiPortofolio } from "./main/ui_portofolio";
import { Investasi_UiDetailPortofolio } from "./detail/ui_detail_portofolio";
import { Investasi_UiDetailProspektus } from "./detail/ui_detail_prospektus";
import { Investasi_UiDaftarDokmen } from "./detail/ui_daftar_dokumen";
import { Investasi_UiEditDokumen } from "./edit/ui_edit_dokumen";
import { Investasi_UiEditInvestasi } from "./edit/ui_edit_investasi";
import { Investasi_UiEditProspektus } from "./edit/ui_edit_prospektus";
import { Investasi_UiCreateDocument } from "./create/ui_create_document";
import { Investasi_UiRekapDokumen } from "./detail/ui_rekap_dokumen";

export { Investasi_UiProsesPembelian };
export { Investasi_UiMetodePembayaran };
export { Investasi_UiFileViewProspektus as Investasi_UiFileView };
export { Investasi_UiInvoice };
export { Investasi_UiProsesTransaksi };
export { Investasi_UiBeranda };
export { Investasi_UiLayoutMain };
export { Investasi_UiDaftarTransaksi };
export { Investasi_UiTransaksiBerhasil };
export { Investasi_UiFileViewDokumen };
export { Investasi_UiSahamSaya };
export { Investasi_UiDetailSahamSaya };
export { Investasi_UiPortofolio };
export { Investasi_UiDetailPortofolio };
export { Investasi_UiDetailProspektus };
export { Investasi_UiDaftarDokmen };
export { Investasi_UiEditDokumen };
export { Investasi_UiEditInvestasi };
export { Investasi_UiEditProspektus };
export { Investasi_UiCreateDocument };
export { Investasi_UiRekapDokumen };
