import { Investasi_ViewDetailSahamSaya } from "./detail/view_detail_saham_saya";
import PdfToImage from "./file_view/view_file_viewer";
import { Investasi_ViewBeranda } from "./main/view_beranda";
import { Investasi_ViewPortofolio } from "./main/view_portofolio";
import { Investasi_ViewPortofolioReview } from "./main/portofolio/view_portofolio_review";
import { Investasi_ViewSahamSaya } from "./main/view_saham_saya";
import { Investasi_ViewTransaksiBerhasil } from "./status_transaksi/view_invoice_berhasil";
import { Investasi_ViewTransaksiGagal } from "./status_transaksi/view_transaksi_gagal";
import { Investasi_ViewInvoice } from "./transaksi/view_invoice";
import { Investasi_ViewMetodePembayaran } from "./transaksi/view_metode_pembayaran";
import { Investasi_ViewProsesPembelian } from "./transaksi/view_proses_pembelian";
import { Investasi_ViewProsesTransaksi } from "./transaksi/view_proses_transaksi";
import Investasi_ViewDetailPublish from "./detail/portofolio/view_detail_publish";
import Investasi_ViewDetailReview from "./detail/portofolio/view_detail_review";
import Investasi_ViewDetailDraft from "./detail/portofolio/view_detail_draft";
import Investasi_ViewDetailReject from "./detail/portofolio/view_detail_reject";
import { Investasi_ViewDetailProspektus } from "./detail/view_detail_prospektusl";
import { Investasi_ViewDaftarDokumen } from "./detail/view_daftar_dokemen";
import { Investasi_ViewEditDokumen } from "./edit/view_edit_dokumen";
import { Investasi_ViewEditInvestasi } from "./edit/view_edit_investasi";
import { Investasi_ViewEditProspektus } from "./edit/view_edit_prospektus";
import { Investasi_ViewCreateDocument } from "./create/view_create_document";
import { Investasi_ViewRekapDokumen } from "./detail/view_rekap_dokumen";
import { Investasi_ViewDetailMain } from "./detail/view_detail_main";
import { Investasi_ViewRekapBerita } from "./detail/view_rekap_berita";
import { Investasi_ViewDaftarBerita } from "./detail/view_daftar_berita";
import { Investasi_ViewCreateBerita } from "./create/view_create_berita";
import { Investasi_ViewDetailBerita } from "./detail/view_berita";

export { Investasi_ViewProsesPembelian };
export { Investasi_ViewMetodePembayaran };
export { Investasi_ViewInvoice };
export { Investasi_ViewProsesTransaksi };
export { Investasi_ViewBeranda };
export { Investasi_ViewTransaksiGagal };
export { Investasi_ViewTransaksiBerhasil };
export { PdfToImage as Investasi_ViewFileViewer };
export { Investasi_ViewSahamSaya };
export { Investasi_ViewDetailSahamSaya };
export { Investasi_ViewPortofolio };
export { Investasi_ViewDetailPublish };
export { Investasi_ViewDetailReview };
export { Investasi_ViewDetailDraft };
export { Investasi_ViewDetailReject };
export { Investasi_ViewDetailProspektus };
export { Investasi_ViewDaftarDokumen };
export { Investasi_ViewEditDokumen };
export { Investasi_ViewEditInvestasi };
export { Investasi_ViewEditProspektus };
export { Investasi_ViewCreateDocument };
export { Investasi_ViewRekapDokumen };
export { Investasi_ViewDetailMain };
export { Investasi_ViewRekapBerita };
export { Investasi_ViewDaftarBerita };
export { Investasi_ViewCreateBerita };
export { Investasi_ViewDetailBerita };
