export type IAdmin_ActivePage = "Main" | "Investasi" | "Donasi" | "Event" | "Voting" | "Job" | "Forum" | "Collaboration"
export type IAdmin_ActiveChildId =
  | "Investasi_1"
  | "Investasi_2"
  | "Investasi_3"
  | "Investasi_4"
  | "Donasi_1"
  | "Donasi_2"
  | "Donasi_3"
  | "Donasi_4"
  | "Donasi_5"
  | "Event_1"
  | "Event_2"
  | "Event_3"
  | "Event_4"
  | "Event_5"
  | "Event_6"
  | "Voting_1"
  | "Voting_2"
  | "Voting_3"
  | "Voting_4"
  | "Voting_5"
  | "Job_1"
  | "Job_2"
  | "Job_3"
  | "Job_4"
  | "Forum_1"
  | "Forum_2"
  | "Forum_3"
  | "Forum_4"
  | "Collaboration_1"
  | "Collaboration_2"
  | "Collaboration_3"
  | "Collaboration_4";


